### ISSUE TITLE
[Bug] 自动跑商购买问题

### ISSUE THREAD

**Issue by fatinghenji** [Night-stars-1/Auto_Resonance#17]
### 问题描述

购买时点击位置错误，导致点击结果是商品描述而非商品购买。

### 预期行为

购买商品

### 实际行为

打开商品描述

### 程序版本

v1.0.2-beta.5

### 日志

无

**Comment by Night-stars-1** [comment]
麻烦给一下商品名称

**Comment by Night-stars-1** [comment]
无法复现

**Comment by fatinghenji** [comment]
抱歉没有及时回复，应该是曼德矿场的图形加速卡。

**Comment by Night-stars-1** [comment]
> 抱歉没有及时回复，应该是曼德矿场的图形加速卡。

这个问题貌似最新版已经修复了
