### ISSUE TITLE
[Bug] 当前跑商配置中进货书不允许为零

### ISSUE THREAD

**Issue by nagisa-eevee** [Night-stars-1/Auto_Resonance#42]
### 问题描述

跑商配置中，若设置进货书为0，提示“未配置进货书，单书利润为0”。

### 预期行为

应当和使用进货书的情况一样，返回不使用进货书下的最优货物和抬价砍价方案

### 实际行为

弹窗提示“未配置进货书，单书利润为0”，无法进行下一步操作

### 截图或录屏

![屏幕截图 2024-04-26 191513](https://github.com/Night-stars-1/Auto_Resonance/assets/46982956/add4ecb6-5686-464c-9ddc-545f6cb0c1d9)

### 程序版本

1.0.9

### 日志

返回主界面
当前站点: 7号自由港
没有数据

**Comment by Night-stars-1** [comment]
感谢反馈

**Comment by Night-stars-1** [comment]
跑商的算法在优化，这个问题后面会更改
