### ISSUE TITLE
[功能请求] 行车途中自动拾取掉落物

### ISSUE THREAD

**Issue by Lu-Jiejie** [Night-stars-1/Auto_Resonance#54]
### 原因

替代 `无人机支援礼包` ，自动在行车途中拾取沿途的掉落物。拾取到的 `加速弹丸` 能大幅提升倒货速度。

### 功能简述

自动在行进路上拾取沿途的掉落物。

### 功能逻辑

设置中添加一个与 `自动使用加速弹丸` 同级的选项，以开启该功能。开启后，行车监听时会自动拾取沿途掉落物。

### 实现参考

我曾在 `mumu模拟器` 的 `操作录制` 中实现过这个功能。该功能只需要模拟连续点击列车右侧的某一点位即可拾取到9成以上的掉落物。

**Comment by Night-stars-1** [comment]
感谢反馈
