### ISSUE TITLE
[BUG] Updater无法正常完成更新

### ISSUE THREAD

**Issue by helloyujiaxu** [Night-stars-1/Auto_Resonance#59]
### 问题描述

在正确完成下载并解压之后，不会执行覆盖新版本文件的操作，但并没有报错。

### 预期行为

在下载并解压新版本到temp文件夹之后，会将新版本文件夹内的文件覆盖到上一级文件夹内。

### 实际行为

解压完成后**没有覆盖文件**就自动退出，并没有报错。
此时temp文件夹内并没有清空，在第二次打开updater.exe才清空。

### 程序版本

1.1.6（更新前版本）

### 日志

updater没有log文件。

**Comment by Night-stars-1** [comment]
感谢反馈

**Comment by Night-stars-1** [comment]
#61
