### ISSUE TITLE
跑商测试报错，无法自动跑商

### ISSUE THREAD

**Issue by 1139365165** [Night-stars-1/Auto_Resonance#78]
### 问题描述

跑商测试报错，无法自动跑商

### 预期行为

跑商测试报错，无法自动跑商

### 实际行为

跑商测试报错，无法自动跑商

### 截图或录屏

![微信截图_20241021174435](https://github.com/user-attachments/assets/134bea4c-e7ea-467b-b81a-f4795ae6d237)

### 程序版本

1.2.5

### 日志

崩溃信息:
Traceback (most recent call last):

> File "app\common\worker.py", line 27, in run

  File "core\api\srap.py", line 34, in get_goods_info

Exception: 请求失败: {"status":false,"message":"发生错误","data":{}}
崩溃信息:
Traceback (most recent call last):

> File "app\common\worker.py", line 27, in run

  File "core\api\srap.py", line 34, in get_goods_info

Exception: 请求失败: {"status":false,"message":"发生错误","data":{}}

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/Auto_Resonance/releases/tag/v1.2.6
