### ISSUE TITLE
能适配雷电模拟器吗？

### ISSUE THREAD

**Issue by zxc173123** [Night-stars-1/Auto_Resonance#81]
### 原因

。

### 功能简述

。

### 功能逻辑

。

### 实现参考

。

**Comment by Night-stars-1** [comment]
支持所有模拟器

**Comment by zxc173123** [comment]
> 支持所有模拟器

试了不支持，端口是我用别的游戏脚本获取的。
![QQ截图20241026230732](https://github.com/user-attachments/assets/1284298d-51a3-4f96-977e-c2e0035d6ca6)
![QQ截图20241026230652](https://github.com/user-attachments/assets/fc1ace37-8463-4496-9de2-de02b793fc4f)

**Comment by Night-stars-1** [comment]
这什么你获取的端口是错误的

**Comment by zxc173123** [comment]
> 这说明你获取的端口是错误的

是正确的我用别的ADB脚本能链接上，是你脚本没适配吧？
开自动是未知ADB端口信息识别不上。希望适配一下雷电的端口
![QQ截图20241027072227](https://github.com/user-attachments/assets/87d860d4-2c25-4b27-984c-6db73397be80)

**Comment by zxc173123** [comment]
> 这说明你获取的端口是错误的

是正确的我用别的ADB脚本能链接上，是你脚本没适配吧？
开自动是未知ADB端口信息识别不上。希望适配一下雷电的端口
![QQ截图20241027072227](https://github.com/user-attachments/assets/87d860d4-2c25-4b27-984c-6db73397be80)

**Comment by Night-stars-1** [comment]
> > 这说明你获取的端口是错误的
> 
> 是正确的我用别的ADB脚本能链接上，是你脚本没适配吧？ 开自动是未知ADB端口信息识别不上。希望适配一下雷电的端口 ![QQ截图20241027072227](https://private-user-images.githubusercontent.com/56154254/380458110-87d860d4-2c25-4b27-984c-6db73397be80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDc4ODcsIm5iZiI6MTczMDAwNzU4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTgxMTAtODdkODYwZDQtMmMyNS00YjI3LTk4NGMtNmRiNzMzOTdiZTgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA1Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTkzMWY2ODFjMDYxODZiNWVhZDhiY2E1M2Y3YTBkYjNlZGY4ZmExMWFmNWRkNWE5YWI3MWE3NWZjNWY3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pg0GLl5WzNPG2DLXJs6dmLvF7MFlMtqhJCBx-7sBTek)

adb的谷歌的应用，android也是谷歌的，你觉得存在没适配的可能没

**Comment by zxc173123** [comment]
> > > 这说明你获取的端口是错误的
> > 
> > 
> > 是正确的我用别的ADB脚本能链接上，是你脚本没适配吧？ 开自动是未知ADB端口信息识别不上。希望适配一下雷电的端口 ![QQ截图20241027072227](https://private-user-images.githubusercontent.com/56154254/380458110-87d860d4-2c25-4b27-984c-6db73397be80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDc4ODcsIm5iZiI6MTczMDAwNzU4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTgxMTAtODdkODYwZDQtMmMyNS00YjI3LTk4NGMtNmRiNzMzOTdiZTgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA1Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTkzMWY2ODFjMDYxODZiNWVhZDhiY2E1M2Y3YTBkYjNlZGY4ZmExMWFmNWRkNWE5YWI3MWE3NWZjNWY3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pg0GLl5WzNPG2DLXJs6dmLvF7MFlMtqhJCBx-7sBTek)
> 
> adb的谷歌的应用，android也是谷歌的，你觉得存在没适配的可能没

所以说为啥连不上呢？我用明日方舟MAA连接这个端口是能正常运行的，还是说这脚本不支持雷电模拟器吗？
![QQ截图20241027135517](https://github.com/user-attachments/assets/7cc5176d-1a0d-4c66-8d98-401c1439f5a8)

**Comment by Night-stars-1** [comment]
> 所以说为啥连不上呢？我用明日方舟MAA连接这个端口是能正常运行的，还是说这脚本不支持雷电模拟器吗？ ![QQ截图20241027135517](https://private-user-images.githubusercontent.com/56154254/380471129-7cc5176d-1a0d-4c66-8d98-401c1439f5a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTAyOTUsIm5iZiI6MTczMDAwOTk5NSwicGF0aCI6Ii81NjE1NDI1NC8zODA0NzExMjktN2NjNTE3NmQtMWEwZC00YzY2LThkOTgtNDAxYzE0MzlmNWE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YWZlNmM1YTgyNzUyZDNlOTZmZDk3ZDRkN2VmNmNhMjQxZWY0NTA5OTI0ZTc0ZWVhMzgxY2MyZDFhNTk5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zO3SqO4QS_Eo4oBcgHzJbRAV4MDKDaAmXROymiatSj4)

这是你自己的问题，你应该百度也不是问我，你没有提供任何有效信息，我无法提供建议
这是我刚下载的雷电模拟器，很明显不存在兼容问题
其次只支持部分模拟器说的是自动连接，只要支持adb的设备都是支持的
![image](https://github.com/user-attachments/assets/4993431e-ea91-4cf5-94b9-0613db305acb)

**Comment by zxc173123** [comment]
> > 所以说为啥连不上呢？我用明日方舟MAA连接这个端口是能正常运行的，还是说这脚本不支持雷电模拟器吗？ ![QQ截图20241027135517](https://private-user-images.githubusercontent.com/56154254/380471129-7cc5176d-1a0d-4c66-8d98-401c1439f5a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTAyOTUsIm5iZiI6MTczMDAwOTk5NSwicGF0aCI6Ii81NjE1NDI1NC8zODA0NzExMjktN2NjNTE3NmQtMWEwZC00YzY2LThkOTgtNDAxYzE0MzlmNWE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YWZlNmM1YTgyNzUyZDNlOTZmZDk3ZDRkN2VmNmNhMjQxZWY0NTA5OTI0ZTc0ZWVhMzgxY2MyZDFhNTk5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zO3SqO4QS_Eo4oBcgHzJbRAV4MDKDaAmXROymiatSj4)
> 
> 这是你自己的问题，你应该百度也不是问我，你没有提供任何有效信息，我无法提供建议 这是我刚下载的雷电模拟器，很明显不存在兼容问题 其次只支持部分模拟器说的是自动连接，只要支持adb的设备都是支持的 ![image](https://private-user-images.githubusercontent.com/99261160/380472277-4993431e-ea91-4cf5-94b9-0613db305acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTI3MzksIm5iZiI6MTczMDAxMjQzOSwicGF0aCI6Ii85OTI2MTE2MC8zODA0NzIyNzctNDk5MzQzMWUtZWE5MS00Y2Y1LTk0YjktMDYxM2RiMzA1YWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA3MDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmE4M2M5Mzg4Njc2NjFjNGUxNTE1MmYwNjQwNGQzNjVhNGFlYTVmY2U0OGVkZDk5MDViZmZkNTZhNzU5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Py4svDWaOdRGjSF4xXOaslw2lLi_6RO3vGYgF4u7ryk)

淦我甚至重装了模拟器不知道为啥这脚本的ADB端口跟MAA的不一样我就说怎么连不上，然后我就重1开始试到对的端口就连上了，你应该加个端口搜索功能，那个自动识别识别不到雷电模拟器的端口。

**Comment by ABA2396** [comment]
雷电用的不是 ip:端口，是直接做成设备名了，所以不能 localhost:端口号 的形式去，得直接用 emulator-5554
