### ISSUE TITLE
[Bug] 自动跑商到站以后，会点击到小地图右上角的手册导致卡死

### ISSUE THREAD

**Issue by hxdhao** [Night-stars-1/Auto_Resonance#86]
### 问题描述

 自动跑商到站以后，会点击到小地图右上角的手册导致卡死

### 预期行为

访问城市并进行商品购买

### 实际行为

点击手册导致卡死

### 截图或录屏

![{32F51B32-E56E-42EE-A9B8-4E272C4DA228}](https://github.com/user-attachments/assets/175fa4e3-d064-49f7-9a07-687266e0b6b7)

### 程序版本

1.2.7

### 日志

无

**Comment by hxdhao** [comment]
下载到的1.2.7的源码中，core文件夹->preset文件夹->station.py文件，def wait_home，等待返回主界面，最后的行为是点击坐标（250，27），该坐标和手册的坐标相近有时导致误触。

**Comment by Night-stars-1** [comment]
1.3.1已修复
