### ISSUE TITLE
[Bug] 跑商启动异常

### ISSUE THREAD

**Issue by Narcis64** [Night-stars-1/Auto_Resonance#90]
### 问题描述

开始跑商时在返回主界面后会点击启程按键进入地图界面，但是程序此时却再次点击访问城市按键，并在城市界面执行点击站点

### 预期行为

返回主界面-点击启程-选择站点

### 实际行为

返回主界面-点击访问城市-选择站点

### 程序版本

1.2.8

### 日志

18:48:40 - INFO	| adb.connect:57 -  ADB端口： 5555 来自: 自定义ADB端口
18:48:40 - INFO	| control.go_home:246 -  返回主界面
18:48:41 - DEBUG	| image.match_screenshot:61 -  min_val=0.44968366622924805, max_val=0.9998355507850647, min_loc=(625, 678), max_loc=(1167, 651)
18:48:43 - DEBUG	| ocr.predict:70 -  [{'text': '7号自由港', 'score': 0.9596495628356934, 'position': [[180.0, 541.0], [324.0, 540.0], [324.0, 567.0], [180.0, 569.0]]}]
18:48:43 - INFO	| presets.get_city:286 -  当前站点: 7号自由港
18:48:43 - INFO	| main.run:71 -  海角城->铁盟哨站
18:48:43 - INFO	| control.go_home:246 -  返回主界面
18:48:43 - DEBUG	| image.match_screenshot:61 -  min_val=0.4870256781578064, max_val=0.8453193306922913, min_loc=(626, 545), max_loc=(477, 114)
18:48:45 - DEBUG	| image.match_screenshot:61 -  min_val=0.8262481093406677, max_val=0.9999892711639404, min_loc=(164, 22), max_loc=(158, 14)
18:48:46 - DEBUG	| image.match_screenshot:61 -  min_val=0.4840890169143677, max_val=0.8358081579208374, min_loc=(626, 543), max_loc=(80, 431)
18:48:48 - DEBUG	| image.match_screenshot:61 -  min_val=0.868316113948822, max_val=0.9052336812019348, min_loc=(154, 9), max_loc=(164, 21)
18:48:48 - DEBUG	| image.match_screenshot:61 -  min_val=0.46853920817375183, max_val=0.9998355507850647, min_loc=(632, 678), max_loc=(1167, 651)
18:48:48 - INFO	| presets.click_station:76 -  点击站点 => 海角城
18:48:49 - DEBUG	| image.match_screenshot:61 -  min_val=0.4599185287952423, max_val=0.9998355507850647, min_loc=(631, 678), max_loc=(1167, 651)
18:48:49 - INFO	| presets.click_station:80 -  检测到主地图界面，识别站点
18:48:49 - INFO	| control.go_home:246 -  返回主界面
18:48:50 - DEBUG	| image.match_screenshot:61 -  min_val=0.454665869474411, max_val=0.9998355507850647, min_loc=(604, 678), max_loc=(1167, 651)
18:48:51 - DEBUG	| ocr.predict:70 -  [{'text': '7号自由港', 'score': 0.9593358039855957, 'position': [[180.0, 541.0], [324.0, 540.0], [324.0, 567.0], [180.0, 569.0]]}]
18:48:51 - INFO	| presets.get_city:286 -  当前站点: 7号自由港
18:48:52 - INFO	| presets.multiple_slide_click_station:176 -  多次滑动点击站点 => 海角城
18:48:53 - DEBUG	| image.match_screenshot:61 -  min_val=0.497965931892395, max_val=0.8477239608764648, min_loc=(627, 540), max_loc=(477, 109)
18:48:54 - DEBUG	| image.match_screenshot:61 -  min_val=0.4851034879684448, max_val=0.8358081579208374, min_loc=(626, 545), max_loc=(80, 431)
18:48:54 - INFO	| presets.select_station:189 -  尝试点击站点 => 0
18:48:54 - DEBUG	| image.match_screenshot:61 -  min_val=0.04883681237697601, max_val=0.9112383127212524, min_loc=(331, 398), max_loc=(779, 31)
18:48:55 - INFO	| presets.select_station:189 -  尝试点击站点 => 1
18:48:56 - DEBUG	| image.match_screenshot:61 -  min_val=0.0788201317191124, max_val=0.9082135558128357, min_loc=(613, 414), max_loc=(779, 31)
18:48:57 - INFO	| presets.select_station:189 -  尝试点击站点 => 2
18:48:58 - DEBUG	| image.match_screenshot:61 -  min_val=0.04795209318399429, max_val=0.9100038409233093, min_loc=(320, 348), max_loc=(779, 31)
18:48:59 - INFO	| presets.select_station:189 -  尝试点击站点 => 3
18:48:59 - DEBUG	| image.match_screenshot:61 -  min_val=0.061584994196891785, max_val=0.9121577739715576, min_loc=(496, 415), max_loc=(778, 31)
18:49:01 - INFO	| presets.select_station:189 -  尝试点击站点 => 4
18:49:01 - DEBUG	| image.match_screenshot:61 -  min_val=0.01751740649342537, max_val=0.9121795296669006, min_loc=(494, 418), max_loc=(778, 31)
18:49:02 - INFO	| presets.select_station:189 -  尝试点击站点 => 5
18:49:03 - DEBUG	| image.match_screenshot:61 -  min_val=0.050561681389808655, max_val=0.910364031791687, min_loc=(208, 417), max_loc=(779, 31)
18:49:04 - INFO	| presets.select_station:189 -  尝试点击站点 => 6
18:49:05 - DEBUG	| image.match_screenshot:61 -  min_val=0.04588838666677475, max_val=0.9110158681869507, min_loc=(514, 484), max_loc=(779, 31)
18:49:06 - INFO	| presets.select_station:189 -  尝试点击站点 => 7
18:49:06 - DEBUG	| image.match_screenshot:61 -  min_val=0.07567018270492554, max_val=0.9107837080955505, min_loc=(502, 485), max_loc=(779, 31)
18:49:08 - INFO	| presets.select_station:189 -  尝试点击站点 => 8
18:49:08 - DEBUG	| image.match_screenshot:61 -  min_val=0.052767910063266754, max_val=0.913979172706604, min_loc=(461, 418), max_loc=(779, 31)
18:49:09 - INFO	| presets.select_station:189 -  尝试点击站点 => 9
18:49:10 - DEBUG	| image.match_screenshot:61 -  min_val=0.05040571093559265, max_val=0.9138998985290527, min_loc=(461, 418), max_loc=(779, 31)
18:49:11 - INFO	| presets.select_station:189 -  尝试点击站点 => 10
18:49:12 - DEBUG	| image.match_screenshot:61 -  min_val=0.1367790848016739, max_val=0.9139605164527893, min_loc=(454, 428), max_loc=(779, 31)
18:49:13 - INFO	| presets.select_station:189 -  尝试点击站点 => 11
18:49:13 - DEBUG	| image.match_screenshot:61 -  min_val=0.12629768252372742, max_val=0.9138630032539368, min_loc=(759, 483), max_loc=(779, 31)
18:49:15 - INFO	| presets.select_station:189 -  尝试点击站点 => 12
18:49:15 - DEBUG	| image.match_screenshot:61 -  min_val=0.04567611962556839, max_val=0.9103611707687378, min_loc=(748, 412), max_loc=(779, 31)
18:49:17 - INFO	| presets.multiple_slide_click_station:202 -  点击前往目的地按钮
18:49:18 - DEBUG	| image.match_screenshot:61 -  min_val=0.6395094394683838, max_val=0.7029036283493042, min_loc=(1019, 612), max_loc=(976, 611)
18:49:18 - DEBUG	| image.match_screenshot:61 -  min_val=0.6385131478309631, max_val=0.7024744749069214, min_loc=(1019, 612), max_loc=(976, 611)
18:49:19 - DEBUG	| image.match_screenshot:61 -  min_val=0.6384721398353577, max_val=0.7019343972206116, min_loc=(1019, 612), max_loc=(976, 611)
18:49:20 - DEBUG	| image.match_screenshot:61 -  min_val=0.6369397640228271, max_val=0.7011940479278564, min_loc=(1019, 612), max_loc=(964, 605)
18:49:20 - DEBUG	| image.match_screenshot:61 -  min_val=0.6359580159187317, max_val=0.7011460065841675, min_loc=(1019, 612), max_loc=(964, 605)
18:49:20 - ERROR	| control.click_image:117 -  未找到指定图片 => resources/map/go_station.png
18:49:21 - DEBUG	| ocr.predict:70 -  [{'text': 'L', 'score': 0.23870113492012024, 'position': [[5.0, 5.0], [22.0, 5.0], [22.0, 13.0], [5.0, 13.0]]}, {'text': '市收厅', 'score': 0.36622896790504456, 'position': [[21.0, 2.0], [77.0, 2.0], [77.0, 16.0], [21.0, 16.0]]}, {'text': '海豹奶茶店', 'score': 0.7734139561653137, 'position': [[282.0, 63.0], [378.0, 64.0], [378.0, 82.0], [282.0, 81.0]]}]
18:49:21 - DEBUG	| ocr.predict:70 -  []
18:49:21 - INFO	| control.click_image:118 -  未知异常-1734173360633
18:49:21 - INFO	| presets.click_station_ocr:227 -  通过OCR识别站点 => 海角城
18:49:21 - DEBUG	| image.match_screenshot:61 -  min_val=0.49163541197776794, max_val=0.8351039886474609, min_loc=(744, 502), max_loc=(198, 387)
18:49:21 - INFO	| presets.select_station:235 -  尝试点击站点 => 0
18:49:23 - DEBUG	| ocr.predict:70 -  []
18:49:23 - INFO	| presets.select_station:243 -  []
18:49:24 - DEBUG	| ocr.predict:70 -  []
18:49:24 - INFO	| presets.select_station:243 -  []
18:49:25 - ERROR	| exceptions.__init__:8 -  停止执行程序

**Comment by Night-stars-1** [comment]
截图一下你的画质设置

**Comment by Narcis64** [comment]
![微信截图_20241215105607](https://github.com/user-attachments/assets/a7e31c67-2796-4e4a-9415-64ca7723ce47)
![微信截图_20241215105627](https://github.com/user-attachments/assets/b05dbebc-d25b-47e5-a87d-cc3499266fce)

**Comment by Narcis64** [comment]
> 截图一下你的画质设置

![微信截图_20241215105607](https://github.com/user-attachments/assets/f8091c48-8cf8-4d4c-871a-f24ec659f285)
![微信截图_20241215105627](https://github.com/user-attachments/assets/eb5543ee-9805-4471-b5d3-571dee314a46)

**Comment by Night-stars-1** [comment]
logs/image文件夹有一个1734173360633.png图片，看一下是卡在哪里了

**Comment by Narcis64** [comment]
> logs/image文件夹有一个1734173360633.png图片，看一下是卡在哪里了

![1734173360633](https://github.com/user-attachments/assets/57c7d00f-c134-40fc-8ebb-aa1f2badd99a)

**Comment by Narcis64** [comment]
1.2.9版本解决了，不过顺便再问一个， 开始启程后选择 ‘立即出发’ 的界面里 如果勾选了本周跳过之后就不再弹出该界面，程序就会在行车的过程乱点了

**Comment by Narcis64** [comment]
1.2.9版本解决了，不过顺便再问一个， 开始启程后选择 ‘立即出发’ 的界面里 如果勾选了本周跳过之后就不再弹出该界面，程序就会在行车的过程乱点了

**Comment by kevinchow9527** [comment]
勉强能用，还是谢谢作者

**Comment by Night-stars-1** [comment]
> 1.2.9版本解决了，不过顺便再问一个， 开始启程后选择 ‘立即出发’ 的界面里 如果勾选了本周跳过之后就不再弹出该界面，程序就会在行车的过程乱点了

1.3.1应该不会乱点了
